<option value="Ball Bearing">Ball Bearing</option>
<option value="Check Valve">Check Valve</option>
<option value="Cooling Unit">Cooling Unit</option>
<option value="Confirmation Box">Confirmation Box</option>
<option value="Equipment Plate">Equipment Plate</option>
<option value="Fuel And Oil Filter">Fuel And Oil Filter</option>
<option value="Fuel Pressure Pump">Fuel Pressure Pump</option>
<option value="Fuel Valve Assembly">Fuel Valve Assembly</option>
<option value="Hydraulic Line">Hydraulic Line</option>
<option value="Lead Lag Damper">Lead Lag Damper</option>
<option value="Oil And Fuel Ceals">Oil And Fuel Ceals</option>
<option value="Oil Pressure Pump">Oil Pressure Pump</option>
<option value="Position Light">Position Light</option>
<option value="Purge Valve">Purge Valve</option>
<option value="Spherical Bearing">Spherical Bearing</option>
<option value="Tail Gear box">Tail Gear box</option>
<option value="Transfer Line">Transfer Line</option>